Exercise 3
MaKu-kodilla/OOP_practice pull request #3
Opened 2018-04-08 09:29 UTC by MaKu-kodilla

Uncaught ReferenceError: Column is not defined at scripts.js:101

wyrzuca mi powyższy błąd.

Mógłbyś zerknąć generalnie na cały kod i napisać co mam poprawić?
Trochę sie pogubiłem w tym zadaniu :/

2018-04-08 16:22 UTC, michal-bootcamp requested changes
dodawanie metod do prototypu kolumny i karty powinno sie odbywac poza funkcja konstruktora

2018-04-09 21:52 UTC, MaKu-kodilla commented
Wydaje mi się, że teraz jest ok :)

2018-04-10 12:36 UTC, michal-bootcamp requested changes
ostyluj aplikacje, zeby wygladala bardziej jak kanban

2018-04-10 12:36 UTC, michal-bootcamp commented on Zadanie 11.3 Własne Trello/index.html
> +        </div>
caly div z klasa `column` jest niepotrzebny, bo wszystkie kolumny wstawiasz js-em

2018-04-11 15:46 UTC, michal-bootcamp requested changes
1. ustawiaj kolumny jedna obok drugiej, w takim stylu: https://www.google.pl/search?q=kanban&source=lnms&tbm=isch&sa=X&ved=0ahUKEwirndbRx7LaAhUGaFAKHaLyD_QQ_AUICygC&biw=1440&bih=727

2. obecnie nie moge przeciagnac karty do kolumny, ktora nie zawiera zadnych kart

2018-04-11 15:46 UTC, michal-bootcamp commented on Zadanie 11.3 Własne Trello/js/scripts.js
> +        placeholder: 'card-placeholder'
ostyluj w css te klase `card-placeholder` (np jakis background-color), dzieki temu przy przeciaganiu kart na inne miejsce bedzie widac gdzie dokladnie ta karta trafi

2018-04-16 09:44 UTC, closed without merging